service: rss-app-node-aws-vboltrukanis
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: us-east-2

plugins:
  - serverless-finch

custom:
  client:
    bucketName: rss-app-node-aws-vboltrukanis
    distributionFolder: build